POST http://localhost:5019/categories
Content-Type: application/json

{
    "name": "Electronics"
}

###

POST http://localhost:5019/products
Content-Type: application/json

{
    "name": "Mechanical Keyboard",
    "price": 2499,
    "categoryId": 1
}

###

GET http://localhost:5019/products

###

GET http://localhost:5019/categories

###

GET http://localhost:5019/categories/1/products